import { join } from "node:path";
import type { Context } from "../core/context.ts";
import { DldError } from "../core/errors.ts";
import { writeFileAtomic } from "../core/files.ts";
import type { Adapter } from "./adapters.ts";
import { parseTemplate, renderBody, type SkillTemplate } from "./template.ts";

export interface GeneratedFile {
  content: string;
  /** 0o755 or 0o644: git records only whether a file is executable. */
  mode: number;
}

/** Output files keyed by `/`-separated path relative to the output directory. */
export type GeneratedFiles = Map<string, GeneratedFile>;

const MANIFEST = "SKILL.md";
const normalMode = (mode: number) => (mode & 0o111 ? 0o755 : 0o644);

/**
 * Files under `dir`, relative and `/`-separated; names starting with `.` are skipped. Anything
 * that is neither a regular file nor a directory (a symlink) is passed to `other`.
 */
function listFiles(
  ctx: Context,
  dir: string,
  other: (rel: string) => void = () => {},
  prefix = "",
): string[] {
  if (!ctx.fs.isDirectory(dir)) return [];
  const found: string[] = [];
  for (const entry of ctx.fs.readDir(dir).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    if (entry.name.startsWith(".")) continue;
    const rel = `${prefix}${entry.name}`;
    if (entry.isDirectory) {
      found.push(...listFiles(ctx, join(dir, entry.name), other, `${rel}/`));
    } else {
      if (!entry.isFile) other(rel);
      found.push(rel);
    }
  }
  return found;
}

const utf8 = new TextDecoder("utf-8", { fatal: true });

/** A supporting file's text; symlinks and files that are not UTF-8 are rejected. */
function readSupportingFile(ctx: Context, path: string, source: string): string {
  try {
    return utf8.decode(ctx.fs.readBytes(path));
  } catch (error) {
    if (error instanceof TypeError) throw new DldError(`${source}: not UTF-8 text`);
    throw error;
  }
}

// @decision(DL-033)
function manifest(
  template: SkillTemplate,
  adapter: Adapter,
  { body, usesDld }: { body: string; usesDld: boolean },
  version: string,
) {
  const fields = adapter.fields.flatMap((field) => template.lines[field] ?? []);
  return [
    "---",
    ...fields,
    ...adapter.extraFrontmatter,
    ...(usesDld ? adapter.dldFrontmatter : []),
    "metadata:",
    `  dld-kit-version: "${version}"`,
    "---",
    `<!-- Generated by dld-kit from ${template.source}. Do not edit; edit the template and run npm run generate. -->`,
    body,
  ].join("\n");
}

// @decision(DL-032)
export interface GenerateOptions {
  /** The templates directory as named in the generated-file notice. */
  sourceDir?: string;
  /**
   * Built files added to the output, keyed `<skill>/<path>`, such as the bundled CLI at
   * `dld-common/scripts/dld.mjs` (DL-035). Placeholders can reference them like template files.
   */
  extraFiles?: ReadonlyMap<string, GeneratedFile>;
}

// @decision(DL-032) @decision(DL-035)
/**
 * Renders every skill under `templatesDir` (`<skill>/SKILL.md` plus supporting files) for
 * `adapter`, adding `extraFiles` to the output.
 */
export function generateSkills(
  ctx: Context,
  templatesDir: string,
  adapter: Adapter,
  version: string,
  { sourceDir = "templates/skills", extraFiles = new Map() }: GenerateOptions = {},
): GeneratedFiles {
  const skills = ctx.fs
    .readDir(templatesDir)
    .filter((entry) => entry.isDirectory && !entry.name.startsWith("."))
    .map((entry) => entry.name)
    .sort();
  const provided = new Set<string>();
  const support = new Map<string, string[]>();
  for (const skill of skills) {
    const files = listFiles(ctx, join(templatesDir, skill), (rel) => {
      throw new DldError(`${sourceDir}/${skill}/${rel}: templates must be regular files`);
    }).filter((file) => file !== MANIFEST);
    support.set(skill, files);
    for (const file of files) provided.add(`${skill}/${file}`);
  }
  for (const path of extraFiles.keys()) {
    if (provided.has(path)) throw new DldError(`${sourceDir}/${path}: also generated; remove it`);
    provided.add(path);
  }

  const output: GeneratedFiles = new Map();
  for (const skill of skills) {
    const path = join(templatesDir, skill, MANIFEST);
    const source = `${sourceDir}/${skill}/${MANIFEST}`;
    const template = parseTemplate(ctx.fs.readFile(path), skill, source);
    const rendered = renderBody(template, {
      exists: (ref) => provided.has(`${ref.skill}/${ref.path}`),
      script: (ref) => adapter.scriptRef(skill, ref),
      dld: () => adapter.dld(skill),
      dldSetup: () => adapter.dldSetup(skill),
    });
    if (!template.internal || adapter.internalManifest) {
      output.set(`${skill}/${MANIFEST}`, {
        content: manifest(template, adapter, rendered, version),
        mode: 0o644,
      });
    }
    for (const file of support.get(skill) ?? []) {
      const full = join(templatesDir, skill, file);
      output.set(`${skill}/${file}`, {
        content: readSupportingFile(ctx, full, `${sourceDir}/${skill}/${file}`),
        mode: normalMode(ctx.fs.fileMode(full)),
      });
    }
  }
  for (const [path, file] of extraFiles) output.set(path, { ...file, mode: normalMode(file.mode) });
  return new Map([...output].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
}

export interface OutputDiff {
  changed: string[];
  missing: string[];
  extra: string[];
}

/** Skill directories the generator owns in an output: those it generates, and any `dld-*`. */
function ownedSkill(path: string, files: GeneratedFiles, generated: Set<string>): boolean {
  const skill = path.split("/", 1)[0] ?? "";
  return generated.has(skill) || skill.startsWith("dld-") || files.has(path);
}

// @decision(DL-033)
/**
 * How the files under `dir` differ from `files`, by content and executable bit. Only skill
 * directories the generator owns are compared, so other skills in the same directory (e.g. a
 * project's own `.claude/skills/`) are never reported or removed.
 */
export function diffOutput(ctx: Context, dir: string, files: GeneratedFiles): OutputDiff {
  const generated = new Set([...files.keys()].map((path) => path.split("/", 1)[0] ?? ""));
  const existing = new Set(
    listFiles(ctx, dir).filter((path) => ownedSkill(path, files, generated)),
  );
  const diff: OutputDiff = { changed: [], missing: [], extra: [] };
  for (const [path, file] of files) {
    const full = join(dir, path);
    if (!existing.has(path) || !ctx.fs.isRegularFile(full)) diff.missing.push(path);
    else if (
      ctx.fs.readFile(full) !== file.content ||
      normalMode(ctx.fs.fileMode(full)) !== file.mode
    ) {
      diff.changed.push(path);
    }
  }
  diff.extra = [...existing].filter((path) => !files.has(path)).sort();
  return diff;
}

// @decision(DL-033)
/**
 * Makes the owned skill directories under `dir` hold exactly `files`: writes what differs and
 * deletes the rest. Emptied directories are left in place.
 */
export function writeOutput(ctx: Context, dir: string, files: GeneratedFiles): OutputDiff {
  const diff = diffOutput(ctx, dir, files);
  for (const path of diff.extra) ctx.fs.remove(join(dir, path));
  for (const path of [...diff.missing, ...diff.changed]) {
    const file = files.get(path);
    if (file === undefined) continue;
    const full = join(dir, path);
    ctx.fs.mkdir(join(full, ".."));
    if (ctx.fs.lexists(full) && !ctx.fs.isRegularFile(full)) ctx.fs.remove(full);
    writeFileAtomic(ctx, full, file.content, file.mode);
  }
  return diff;
}
