import { join } from "node:path";
import type { Context } from "../core/context.ts";
import { writeFileAtomic } from "../core/files.ts";
import type { Adapter } from "./adapters.ts";
import { parseTemplate, renderBody, type SkillTemplate } from "./template.ts";

export interface GeneratedFile {
  content: string;
  /** 0o755 or 0o644: git records only whether a file is executable. */
  mode: number;
}

/** Output files keyed by `/`-separated path relative to the output directory. */
export type GeneratedFiles = Map<string, GeneratedFile>;

const MANIFEST = "SKILL.md";
const normalMode = (mode: number) => (mode & 0o111 ? 0o755 : 0o644);

/** Regular files under `dir`, relative and `/`-separated; names starting with `.` are skipped. */
function listFiles(ctx: Context, dir: string, prefix = ""): string[] {
  if (!ctx.fs.isDirectory(dir)) return [];
  const found: string[] = [];
  for (const entry of ctx.fs.readDir(dir).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    if (entry.name.startsWith(".")) continue;
    const rel = `${prefix}${entry.name}`;
    if (entry.isDirectory) found.push(...listFiles(ctx, join(dir, entry.name), `${rel}/`));
    else found.push(rel);
  }
  return found;
}

// @decision(DL-033)
function manifest(template: SkillTemplate, adapter: Adapter, body: string, version: string) {
  const fields = adapter.fields.flatMap((field) => template.lines[field] ?? []);
  return [
    "---",
    ...fields,
    ...adapter.extraFrontmatter,
    "metadata:",
    `  dld-kit-version: "${version}"`,
    "---",
    `<!-- Generated by dld-kit from ${template.source}. Do not edit; edit the template and run npm run generate. -->`,
    body,
  ].join("\n");
}

// @decision(DL-032)
/**
 * Renders every skill under `templatesDir` (`<skill>/SKILL.md` plus supporting files) for
 * `adapter`. `sourceDir` is the templates directory as named in the generated-file notice.
 */
export function generateSkills(
  ctx: Context,
  templatesDir: string,
  adapter: Adapter,
  version: string,
  sourceDir = "templates/skills",
): GeneratedFiles {
  const skills = ctx.fs
    .readDir(templatesDir)
    .filter((entry) => entry.isDirectory && !entry.name.startsWith("."))
    .map((entry) => entry.name)
    .sort();
  const provided = new Set<string>();
  const support = new Map<string, string[]>();
  for (const skill of skills) {
    const files = listFiles(ctx, join(templatesDir, skill)).filter((file) => file !== MANIFEST);
    support.set(skill, files);
    for (const file of files) provided.add(`${skill}/${file}`);
  }

  const output: GeneratedFiles = new Map();
  for (const skill of skills) {
    const path = join(templatesDir, skill, MANIFEST);
    const source = `${sourceDir}/${skill}/${MANIFEST}`;
    const template = parseTemplate(ctx.fs.readFile(path), skill, source);
    const body = renderBody(
      template,
      (ref) => provided.has(`${ref.skill}/${ref.path}`),
      (ref) => adapter.scriptRef(skill, ref),
    );
    if (!template.internal || adapter.internalManifest) {
      output.set(`${skill}/${MANIFEST}`, {
        content: manifest(template, adapter, body, version),
        mode: 0o644,
      });
    }
    for (const file of support.get(skill) ?? []) {
      const full = join(templatesDir, skill, file);
      output.set(`${skill}/${file}`, {
        content: ctx.fs.readFile(full),
        mode: normalMode(ctx.fs.fileMode(full)),
      });
    }
  }
  return output;
}

export interface OutputDiff {
  changed: string[];
  missing: string[];
  extra: string[];
}

// @decision(DL-033)
/** How the files under `dir` differ from `files`, by content and executable bit. */
export function diffOutput(ctx: Context, dir: string, files: GeneratedFiles): OutputDiff {
  const existing = new Set(listFiles(ctx, dir));
  const diff: OutputDiff = { changed: [], missing: [], extra: [] };
  for (const [path, file] of files) {
    const full = join(dir, path);
    if (!existing.has(path) || !ctx.fs.isRegularFile(full)) diff.missing.push(path);
    else if (
      ctx.fs.readFile(full) !== file.content ||
      normalMode(ctx.fs.fileMode(full)) !== file.mode
    ) {
      diff.changed.push(path);
    }
  }
  diff.extra = [...existing].filter((path) => !files.has(path)).sort();
  return diff;
}

// @decision(DL-033)
/** Makes `dir` hold exactly `files`: writes what differs and deletes everything else. */
export function writeOutput(ctx: Context, dir: string, files: GeneratedFiles): OutputDiff {
  const diff = diffOutput(ctx, dir, files);
  for (const path of diff.extra) ctx.fs.remove(join(dir, path));
  for (const path of [...diff.missing, ...diff.changed]) {
    const file = files.get(path);
    if (file === undefined) continue;
    const full = join(dir, path);
    ctx.fs.mkdir(join(full, ".."));
    if (ctx.fs.lexists(full) && !ctx.fs.isRegularFile(full)) ctx.fs.remove(full);
    writeFileAtomic(ctx, full, file.content, file.mode);
  }
  return diff;
}
