import { describe, expect, test } from "bun:test";
import { symlinkSync } from "node:fs";
import { join } from "node:path";
import { fakeContext, memoryFs, tempProject } from "../test-helpers.ts";
import { agentSkillsAdapter, claudeCodeAdapter } from "./adapters.ts";
import { diffOutput, type GeneratedFiles, generateSkills, writeOutput } from "./generate.ts";

const T = "/repo/templates/skills";

function templates() {
  const fs = memoryFs({
    [`${T}/dld-common/SKILL.md`]:
      "---\nname: dld-common\ndescription: Shared.\ninternal: true\ncompatibility: Requires bash.\n---\n\nSee {{script dld-common/scripts/next-id.sh}}.\n",
    [`${T}/dld-common/scripts/next-id.sh`]: "#!/bin/sh\necho DL-001\n",
    [`${T}/dld-common/.DS_Store`]: "junk",
    [`${T}/dld-plan/SKILL.md`]:
      "---\nname: dld-plan\ndescription: Plan.\ncompatibility: Requires bash.\n---\n\nRun {{script dld-common/scripts/next-id.sh}} and {{script dld-plan/scripts/p.sh}}.\n",
    [`${T}/dld-plan/scripts/p.sh`]: "#!/bin/sh\n",
    [`${T}/dld-plan/notes/readme.txt`]: "notes\n",
  });
  fs.chmod(`${T}/dld-common/scripts/next-id.sh`, 0o775);
  return fakeContext({ fs });
}

const NOTICE = (skill: string) =>
  `<!-- Generated by dld-kit from templates/skills/${skill}/SKILL.md. Do not edit; edit the template and run npm run generate. -->`;

describe("generateSkills", () => {
  test("agent-skills: relative script paths, compatibility, internal manifests", () => {
    const files = generateSkills(templates(), T, agentSkillsAdapter, "1.0");
    expect([...files.keys()]).toEqual([
      "dld-common/SKILL.md",
      "dld-common/scripts/next-id.sh",
      "dld-plan/SKILL.md",
      "dld-plan/notes/readme.txt",
      "dld-plan/scripts/p.sh",
    ]);
    expect(files.get("dld-plan/SKILL.md")).toEqual({
      content: `---\nname: dld-plan\ndescription: Plan.\ncompatibility: Requires bash.\nmetadata:\n  dld-kit-version: "1.0"\n---\n${NOTICE("dld-plan")}\n\nRun ../dld-common/scripts/next-id.sh and scripts/p.sh.\n`,
      mode: 0o644,
    });
    expect(files.get("dld-common/scripts/next-id.sh")).toEqual({
      content: "#!/bin/sh\necho DL-001\n",
      mode: 0o755,
    });
    expect(files.get("dld-plan/scripts/p.sh")?.mode).toBe(0o644);
  });

  test("claude-code: prefixed paths, user_invocable, no internal manifests", () => {
    const files = generateSkills(templates(), T, claudeCodeAdapter, "1.0");
    expect(files.has("dld-common/SKILL.md")).toBe(false);
    expect(files.has("dld-common/scripts/next-id.sh")).toBe(true);
    expect(files.get("dld-plan/SKILL.md")?.content).toBe(
      `---\nname: dld-plan\ndescription: Plan.\nuser_invocable: true\nmetadata:\n  dld-kit-version: "1.0"\n---\n${NOTICE("dld-plan")}\n\nRun .claude/skills/dld-common/scripts/next-id.sh and .claude/skills/dld-plan/scripts/p.sh.\n`,
    );
  });

  test("fails on a placeholder naming a file no template provides", () => {
    const ctx = templates();
    ctx.fs.writeFile(
      `${T}/dld-plan/SKILL.md`,
      "---\nname: dld-plan\ndescription: P.\n---\n{{script dld-plan/scripts/missing.sh}}\n",
    );
    expect(() => generateSkills(ctx, T, agentSkillsAdapter, "1.0")).toThrow(
      "templates/skills/dld-plan/SKILL.md:5: no template provides dld-plan/scripts/missing.sh",
    );
  });
});

describe("supporting files", () => {
  test("rejects files that are not UTF-8 text", () => {
    const ctx = templates();
    ctx.fs.readBytes = (path) =>
      path.endsWith("p.sh")
        ? new Uint8Array([0xff, 0xfe])
        : new TextEncoder().encode(ctx.fs.readFile(path));
    expect(() => generateSkills(ctx, T, agentSkillsAdapter, "1.0")).toThrow(
      "templates/skills/dld-plan/scripts/p.sh: not UTF-8 text",
    );
  });

  test("rejects symlinks in templates", () => {
    const p = tempProject(null);
    try {
      const dir = join(p.root, "t");
      p.write("t/dld-x/SKILL.md", "---\nname: dld-x\ndescription: X.\n---\n");
      p.write("t/dld-x/scripts/real.sh", "#!/bin/sh\n");
      symlinkSync("real.sh", join(dir, "dld-x/scripts/link.sh"));
      expect(() => generateSkills(p.ctx, dir, agentSkillsAdapter, "1.0")).toThrow(
        "templates/skills/dld-x/scripts/link.sh: templates must be regular files",
      );
    } finally {
      p.cleanup();
    }
  });
});

describe("diffOutput and writeOutput", () => {
  const files: GeneratedFiles = new Map([
    ["a/SKILL.md", { content: "skill\n", mode: 0o644 }],
    ["a/scripts/run.sh", { content: "#!/bin/sh\n", mode: 0o755 }],
    ["b/SKILL.md", { content: "b\n", mode: 0o644 }],
  ]);

  test("reports changed, missing and extra files, then makes the directory match", () => {
    const fs = memoryFs({
      "/out/a/SKILL.md": "edited\n",
      "/out/a/scripts/run.sh": "#!/bin/sh\n",
      "/out/dld-old/SKILL.md": "stale\n",
      "/out/my-skill/SKILL.md": "the project's own\n",
      "/out/.keep": "",
    });
    const ctx = fakeContext({ fs });
    expect(diffOutput(ctx, "/out", files)).toEqual({
      changed: ["a/SKILL.md", "a/scripts/run.sh"],
      missing: ["b/SKILL.md"],
      extra: ["dld-old/SKILL.md"],
    });
    writeOutput(ctx, "/out", files);
    expect(diffOutput(ctx, "/out", files)).toEqual({ changed: [], missing: [], extra: [] });
    expect(fs.files["/out/a/SKILL.md"]).toBe("skill\n");
    expect(fs.fileMode("/out/a/scripts/run.sh")).toBe(0o755);
    expect("/out/dld-old/SKILL.md" in fs.files).toBe(false);
    expect(fs.files["/out/my-skill/SKILL.md"]).toBe("the project's own\n");
    expect("/out/.keep" in fs.files).toBe(true);
  });

  test("treats a missing output directory as all missing", () => {
    const ctx = fakeContext({ fs: memoryFs({}) });
    expect(diffOutput(ctx, "/none", files).missing).toEqual([...files.keys()]);
  });
});
