import { describe, expect, test } from "bun:test";
import { mkdirSync, symlinkSync } from "node:fs";
import { join } from "node:path";
import { fakeContext, memoryFs, tempProject } from "../test-helpers.ts";
import { AGENTS_LAYOUT, CLAUDE_LAYOUT, type RuleChannel, type SkillLayout } from "./harnesses.ts";
import {
  applyInstall,
  checkDowngrade,
  compareVersions,
  type InstallSource,
  installedLayouts,
  installedStamps,
  installedTargets,
  missingAgentsRuleWarning,
  packageSource,
  planInstall,
} from "./install.ts";
import { CLAUDE_RULE_FILE, renderRuleFile } from "./rule.ts";

const PKG = "/pkg";
const SOURCE: InstallSource = { templatesDir: `${PKG}/templates/skills`, cli: "// cli\n" };

function project(extra: Record<string, string> = {}) {
  const fs = memoryFs({
    [`${PKG}/dist/dld.mjs`]: "// cli\n",
    [`${PKG}/templates/skills/dld-common/SKILL.md`]:
      "---\nname: dld-common\ndescription: Shared.\ninternal: true\n---\n\n{{dld}} --help\n",
    [`${PKG}/templates/skills/dld-plan/SKILL.md`]:
      "---\nname: dld-plan\ndescription: Plan.\n---\n\n{{dld-setup}}\n\n{{dld}} next-id\n",
    ...extra,
  });
  return { fs, ctx: fakeContext({ fs }) };
}

function install(
  ctx: ReturnType<typeof project>["ctx"],
  layouts: SkillLayout[],
  rules: RuleChannel[] = [],
  version = "1.0.0",
  force = false,
) {
  const plan = planInstall(ctx, "/p", {
    source: SOURCE,
    layouts: new Set(layouts),
    rules: new Set(rules),
    version,
    force,
  });
  return applyInstall(ctx, "/p", plan);
}

describe("packageSource", () => {
  test("finds the templates beside the running CLI and reads the CLI itself", () => {
    const { ctx } = project();
    expect(packageSource(ctx, `${PKG}/dist/dld.mjs`, "init")).toEqual(SOURCE);
  });

  test("the copy inside dld-common has no templates and points at the npm package", () => {
    const { ctx } = project();
    expect(() =>
      packageSource(ctx, "/p/.claude/skills/dld-common/scripts/dld.mjs", "update"),
    ).toThrow("Run it from the package instead: npx dld-kit@latest update");
  });
});

describe("planInstall and applyInstall", () => {
  test("installs both layouts and the rule, then reports nothing to do", () => {
    const { fs, ctx } = project();
    const report = install(ctx, [CLAUDE_LAYOUT, AGENTS_LAYOUT], ["claude-file"]);
    expect(report).toEqual({
      skills: [
        { dir: ".claude/skills", written: 2, removed: 0, unchanged: 0 },
        { dir: ".agents/skills", written: 3, removed: 0, unchanged: 0 },
      ],
      ruleWritten: [CLAUDE_RULE_FILE],
      ruleRemoved: [],
      warnings: [],
    });
    expect(fs.files["/p/.agents/skills/dld-common/scripts/dld.mjs"]).toBe("// cli\n");
    expect(fs.fileMode("/p/.agents/skills/dld-common/scripts/dld.mjs")).toBe(0o755);
    expect(fs.files["/p/.claude/skills/dld-plan/SKILL.md"]).toContain('dld-kit-version: "1.0.0"');
    expect(install(ctx, [CLAUDE_LAYOUT, AGENTS_LAYOUT], ["claude-file"]).skills).toEqual([
      { dir: ".claude/skills", written: 0, removed: 0, unchanged: 2 },
      { dir: ".agents/skills", written: 0, removed: 0, unchanged: 3 },
    ]);
    expect(installedLayouts(ctx, "/p")).toEqual([CLAUDE_LAYOUT, AGENTS_LAYOUT]);
  });

  test("replaces a pre-1.0 copy: rewrites its skills and removes its scripts", () => {
    const { fs, ctx } = project({
      "/p/.claude/skills/dld-plan/SKILL.md": "---\nname: dld-plan\n---\nold\n",
      "/p/.claude/skills/dld-common/scripts/next-id.sh": "#!/bin/bash\n",
      "/p/.claude/skills/my-own/SKILL.md": "mine\n",
    });
    const report = install(ctx, [CLAUDE_LAYOUT]);
    expect(report.skills).toEqual([
      { dir: ".claude/skills", written: 2, removed: 1, unchanged: 0 },
    ]);
    expect("/p/.claude/skills/dld-common/scripts/next-id.sh" in fs.files).toBe(false);
    expect(fs.files["/p/.claude/skills/my-own/SKILL.md"]).toBe("mine\n");
  });

  test("refuses to downgrade unless forced, and checks before writing anything", () => {
    const { fs, ctx } = project();
    install(ctx, [AGENTS_LAYOUT], ["claude-file"], "1.2.0");
    expect(() => install(ctx, [AGENTS_LAYOUT], [], "1.1.0")).toThrow(
      "these files were installed by a newer dld-kit than this one (1.1.0):\n  .agents/skills/dld-common/SKILL.md (1.2.0)",
    );
    expect(fs.files["/p/.agents/skills/dld-plan/SKILL.md"]).toContain('"1.2.0"');
    install(ctx, [AGENTS_LAYOUT], ["claude-file"], "1.1.0", true);
    expect(fs.files["/p/.agents/skills/dld-plan/SKILL.md"]).toContain('"1.1.0"');
    expect(fs.files[`/p/${CLAUDE_RULE_FILE}`]).toStartWith("<!-- Generated by dld-kit 1.1.0 ");
  });

  test("installing only the rule needs no templates; skills do", () => {
    const { ctx } = project();
    const plan = planInstall(ctx, "/p", {
      layouts: new Set(),
      rules: new Set(["block"]),
      version: "1.0.0",
      codex: true,
    });
    expect(plan.skills).toEqual([]);
    expect(applyInstall(ctx, "/p", plan).ruleWritten).toEqual(["AGENTS.md"]);
    expect(() =>
      planInstall(ctx, "/p", { layouts: new Set([CLAUDE_LAYOUT]), rules: new Set(), version: "1" }),
    ).toThrow("installing skills needs the skill templates");
  });
});

describe("installed targets", () => {
  test("Claude Code skills imply Claude Code's rule; .agents skills without a rule warn", () => {
    const { ctx } = project();
    install(ctx, [CLAUDE_LAYOUT, AGENTS_LAYOUT]);
    const targets = installedTargets(ctx, "/p");
    expect([...targets.layouts]).toEqual([CLAUDE_LAYOUT, AGENTS_LAYOUT]);
    expect([...targets.rules]).toEqual(["claude-file"]);
    expect(missingAgentsRuleWarning(targets)).toEqual([
      expect.stringContaining(".agents/skills has the DLD skills, but no agent reading it"),
    ]);
    expect(missingAgentsRuleWarning({ ...targets, rules: new Set(["block"]) })).toEqual([]);
  });

  test("refuses to install skills through a symlinked skills directory", () => {
    const p = tempProject(null);
    try {
      p.write(".agents/skills/.keep", "");
      mkdirSync(join(p.root, ".claude"), { recursive: true });
      symlinkSync(join(p.root, ".agents/skills"), join(p.root, ".claude/skills"));
      const request = {
        layouts: new Set([CLAUDE_LAYOUT]),
        rules: new Set<RuleChannel>(),
        version: "1.0.0",
        source: SOURCE,
      };
      expect(() => planInstall(p.ctx, p.root, request)).toThrow(
        ".claude/skills is a symlink; dld-kit does not install through symlinks",
      );
    } finally {
      p.cleanup();
    }
  });
});

describe("version stamps", () => {
  test("installedStamps reads skill and rule stamps; unstamped files have no version", () => {
    const { ctx } = project({
      "/p/.claude/skills/dld-old/SKILL.md": "---\nname: dld-old\n---\n",
      "/p/.claude/skills/dld-empty/notes.txt": "",
      [`/p/${CLAUDE_RULE_FILE}`]: renderRuleFile("claude-file", "x\n", "0.9.0"),
    });
    install(ctx, [AGENTS_LAYOUT], [], "1.0.0");
    expect(installedStamps(ctx, "/p")).toEqual([
      { path: ".claude/skills/dld-old/SKILL.md", version: undefined },
      { path: ".agents/skills/dld-common/SKILL.md", version: "1.0.0" },
      { path: ".agents/skills/dld-plan/SKILL.md", version: "1.0.0" },
      { path: CLAUDE_RULE_FILE, version: "0.9.0" },
    ]);
  });

  test.each([
    ["1.0.0", "1.0.0", 0],
    ["1.0.1", "1.0.0", 1],
    ["1.2.0", "1.10.0", -1],
    ["2.0.0", "2.0.0-rc.1", 1],
    ["2.0.0-rc.1", "2.0.0", -1],
    ["2.0.0-rc.1", "2.0.0-rc.2", -1],
    ["2.0.0-rc.2", "2.0.0-rc.1", 1],
    ["1.0.0+build", "1.0.0", 0],
    ["1.0.0-rc.9", "1.0.0-rc.10", -1],
    ["1.0.0-rc.10", "1.0.0-rc.9", 1],
    ["1.0.0-1", "1.0.0-alpha", -1],
    ["1.0.0-alpha", "1.0.0-1", 1],
    ["1.0.0-alpha", "1.0.0-alpha.1", -1],
    ["1.0.0-alpha", "1.0.0-beta", -1],
  ])("compareVersions(%s, %s) is %d", (a, b, expected) => {
    expect(compareVersions(a, b)).toBe(expected);
  });

  test("unparsable versions never block an install", () => {
    expect(compareVersions("latest", "1.0.0")).toBeUndefined();
    expect(() =>
      checkDowngrade(
        [
          { path: "a", version: "next" },
          { path: "b", version: undefined },
          { path: "c", version: "0.9.0" },
        ],
        "1.0.0",
      ),
    ).not.toThrow();
  });
});
