import { dirname, join, posix } from "node:path";
import ruleText from "../../templates/rules/dld-workflow.md" with { type: "text" };
import { CONFIG_FILE } from "../core/config.ts";
import type { Context } from "../core/context.ts";
import { DldError } from "../core/errors.ts";
import { writeFileAtomic } from "../core/files.ts";
import { HARNESSES, type Harness, type RuleChannel } from "./harnesses.ts";

// @decision(DL-042)
/** The always-on rule, embedded in the bundle so every copy of the CLI can install it. */
export const RULE_TEXT: string = ruleText;
export const RULE_SOURCE = "templates/rules/dld-workflow.md";

export const CLAUDE_RULE_FILE = ".claude/rules/dld-workflow.md";
export const AGENTS_RULE_FILE = ".agents/rules/dld-workflow.md";
/** dld-kit's file that makes Claude Code read AGENTS.md through an import (DL-055). */
export const CLAUDE_IMPORT_FILE = ".claude/CLAUDE.md";
export const BLOCK_START = "<!-- dld-kit:start -->";
export const BLOCK_END = "<!-- dld-kit:end -->";
/** Instruction files that can hold the block, in the order harnesses read them. */
const AGENTS_MD = "AGENTS.md";
const CLAUDE_MD = "CLAUDE.md";
/** Claude Code loads each of these that exists, and reads AGENTS.md directly only without them. */
const CLAUDE_FILES = [CLAUDE_MD, CLAUDE_IMPORT_FILE, "CLAUDE.local.md"];
/** The CLAUDE files a project shares; `CLAUDE.local.md` is personal and usually not committed. */
const SHARED_CLAUDE_FILES = [CLAUDE_MD, CLAUDE_IMPORT_FILE];

type RuleFileChannel = Exclude<RuleChannel, "block">;
const RULE_FILES: Record<RuleFileChannel, string> = {
  "claude-file": CLAUDE_RULE_FILE,
  "agents-file": AGENTS_RULE_FILE,
};

// @decision(DL-044)
function notice(version: string, what: string): string {
  return `<!-- Generated by dld-kit ${version} from ${RULE_SOURCE}. Do not edit: updating the rule overwrites this ${what}. -->`;
}

const STAMP = /<!-- Generated by dld-kit (\S+) from /;

/** The dld-kit version in a rule file's or block's notice, if any. */
export function ruleVersion(content: string): string | undefined {
  return STAMP.exec(content)?.[1];
}

// @decision(DL-045)
/** An owned rule file's content. Antigravity only loads rules marked `always_on` every session. */
export function renderRuleFile(channel: RuleFileChannel, text: string, version: string): string {
  const frontmatter = channel === "agents-file" ? "---\ntrigger: always_on\n---\n" : "";
  return `${frontmatter}${notice(version, "file")}\n\n${text}`;
}

// @decision(DL-055)
/** The import file's content: a notice, then the import of AGENTS.md relative to `.claude/`. */
export function renderImportFile(version: string): string {
  return `<!-- Generated by dld-kit ${version} for Claude Code: it loads AGENTS.md, which holds the DLD rule, through the import below. Do not edit: updating the rule overwrites this file. -->\n\n@../AGENTS.md\n`;
}

const IMPORT_STAMP = /^<!-- Generated by dld-kit (\S+) for Claude Code:/;

/** The dld-kit version of an import file dld-kit owns, or undefined for any other content. */
export function importFileVersion(content: string): string | undefined {
  return IMPORT_STAMP.exec(content)?.[1];
}

/** The managed block's lines, from start marker to end marker. */
export function renderBlock(text: string, version: string): string[] {
  const body = text.endsWith("\n") ? text.slice(0, -1) : text;
  return [BLOCK_START, notice(version, "block"), "", ...body.split("\n"), BLOCK_END];
}

interface BlockSpan {
  /** Offset of the start marker's first character. */
  from: number;
  /** Offset just past the end marker, before its line terminator. */
  to: number;
}

// @decision(DL-045)
/** Where the block sits in `content`, or undefined if there is none. Bad markers are an error. */
export function findBlock(content: string, file: string): BlockSpan | undefined {
  const starts: number[] = [];
  const ends: number[] = [];
  let offset = 0;
  for (const line of content.split("\n")) {
    const text = line.endsWith("\r") ? line.slice(0, -1) : line;
    if (text === BLOCK_START) starts.push(offset);
    if (text === BLOCK_END) ends.push(offset);
    offset += line.length + 1;
  }
  if (starts.length === 0 && ends.length === 0) return undefined;
  const [from] = starts;
  const [end] = ends;
  if (starts.length !== 1 || ends.length !== 1 || from === undefined || end === undefined) {
    throw malformed(file);
  }
  if (end < from) throw malformed(file);
  return { from, to: end + BLOCK_END.length };
}

function malformed(file: string): DldError {
  return new DldError(
    `${file}: expected one '${BLOCK_START}' line followed by one '${BLOCK_END}' line; fix the dld-kit markers by hand`,
  );
}

// @decision(DL-045)
/**
 * `content` with the block replaced, or appended after a blank line. Everything outside the
 * block is unchanged, and the block uses the file's line endings.
 */
export function upsertBlock(content: string, block: readonly string[], file: string): string {
  const eol = content.includes("\r\n") ? "\r\n" : "\n";
  const rendered = block.join(eol);
  const span = findBlock(content, file);
  if (span !== undefined) return content.slice(0, span.from) + rendered + content.slice(span.to);
  if (content === "") return rendered + eol;
  const separator = content.endsWith("\n") ? eol : eol + eol;
  return content + separator + rendered + eol;
}

export interface RulePlan {
  /** Files to write, relative to the project root. */
  writes: { path: string; content: string }[];
  /** Owned rule files to delete, relative to the project root. */
  removals: string[];
  warnings: string[];
}

export interface RuleOptions {
  /** The harnesses being installed for; a block reader that cannot see the block gets a warning. */
  harnesses?: readonly Harness[];
}

// @decision(DL-045)
/**
 * What installing the rule for `channels` changes under `root`. A block already present in
 * AGENTS.md or CLAUDE.md is refreshed where it is; otherwise a new one goes into AGENTS.md, else
 * CLAUDE.md, else a new AGENTS.md. A harness that loads the block's file gets no owned rule file.
 */
export function planRule(
  ctx: Context,
  root: string,
  channels: ReadonlySet<RuleChannel>,
  version: string,
  { harnesses = [] }: RuleOptions = {},
  text: string = RULE_TEXT,
): RulePlan {
  const plan: RulePlan = { writes: [], removals: [], warnings: [] };
  const regular = (file: string) => ctx.fs.isRegularFile(join(root, file));
  const read = (file: string) => (regular(file) ? ctx.fs.readFile(join(root, file)) : "");
  /** The file a harness ends up reading, following symlinks; a file yet to be created is itself. */
  const resolved = (file: string) => {
    const full = join(root, file);
    return ctx.fs.exists(full) ? ctx.fs.realPath(full) : full;
  };

  let blockFiles = [AGENTS_MD, CLAUDE_MD].filter(
    (file) => regular(file) && findBlock(read(file), file) !== undefined,
  );
  if (blockFiles.length === 0 && channels.has("block")) blockFiles = [blockPlacement(ctx, root)];
  // @decision(DL-054) A file about to receive the block counts as existing.
  const pending = new Map<string, string>();
  for (const file of blockFiles) {
    const content = read(file);
    const updated = upsertBlock(content, renderBlock(text, version), file);
    pending.set(file, updated);
    if (updated !== content) plan.writes.push({ path: file, content: updated });
  }

  // @decision(DL-055)
  const linkedDir = symlinkedPart(ctx, root, dirname(CLAUDE_IMPORT_FILE));
  const ownsImport =
    linkedDir === undefined && importFileVersion(read(CLAUDE_IMPORT_FILE)) !== undefined;
  const wantsImport =
    channels.has("claude-file") &&
    blockFiles.includes(AGENTS_MD) &&
    !SHARED_CLAUDE_FILES.some((file) => ctx.fs.lexists(join(root, file)));
  if (ownsImport || (wantsImport && linkedDir === undefined)) {
    const content = renderImportFile(version);
    pending.set(CLAUDE_IMPORT_FILE, content);
    if (read(CLAUDE_IMPORT_FILE) !== content) {
      plan.writes.push({ path: CLAUDE_IMPORT_FILE, content });
    }
  } else if (wantsImport) {
    plan.warnings.push(
      `${linkedDir} is a symlink, so dld-kit does not write ${CLAUDE_IMPORT_FILE}, which would import AGENTS.md for Claude Code. Claude Code reads the rule block in AGENTS.md by itself only while the project has no CLAUDE.md, ${CLAUDE_IMPORT_FILE} or CLAUDE.local.md.`,
    );
  }

  const withBlock = new Set(blockFiles.map(resolved));
  const current = projectView(ctx, root);
  const view: FileView = {
    exists: (file) => pending.has(file) || current.exists(file),
    read: (file) => pending.get(file) ?? current.read(file),
  };
  const reads = (harness: Harness) => instructionFiles(harness, view)[0];
  const readsBlock = (harness: Harness) =>
    instructionFiles(harness, view).some((file) => withBlock.has(resolved(file)));
  const ownerOf = (channel: RuleFileChannel) => HARNESSES.find((h) => h.rule === channel);
  const loadsBlock = (channel: RuleFileChannel) => {
    const owner = ownerOf(channel);
    return owner !== undefined && readsBlock(owner);
  };
  if (blockFiles.length > 0) {
    plan.warnings.push(
      ...blindWarnings(
        blockFiles,
        harnesses.filter((h) => h.rule === "block" && !readsBlock(h)),
        reads,
      ),
    );
  }
  for (const channel of ["claude-file", "agents-file"] as const) {
    const path = RULE_FILES[channel];
    if (loadsBlock(channel)) {
      if (ctx.fs.lexists(join(root, path))) plan.removals.push(path);
    } else if (channels.has(channel)) {
      refuseSymlinkedDir(ctx, root, dirname(path));
      const content = renderRuleFile(channel, text, version);
      if (read(path) !== content) plan.writes.push({ path, content });
    }
  }
  const ruleInstalled = blockFiles.length > 0 || channels.size > 0;
  plan.warnings.push(...legacyBlockWarnings(read(CLAUDE_MD), ruleInstalled));
  return plan;
}

/** Instruction files at the project root, as they are or as a plan leaves them. */
interface FileView {
  exists(file: string): boolean;
  read(file: string): string;
}

/** The files a harness sees: symlinks are followed, and a directory reads as empty. */
function projectView(ctx: Context, root: string): FileView {
  const exists = (file: string) => ctx.fs.exists(join(root, file));
  return {
    exists,
    read: (file) =>
      exists(file) && !ctx.fs.isDirectory(join(root, file))
        ? ctx.fs.readFile(join(root, file))
        : "",
  };
}

// @decision(DL-045) @decision(DL-049) @decision(DL-054) @decision(DL-055)
/**
 * The instruction files `harness` reads. Most harnesses read the first of their list that
 * exists. Claude Code reads every CLAUDE file that exists, plus AGENTS.md when one of them imports
 * it; with no CLAUDE file, it reads AGENTS.md directly.
 */
function instructionFiles(harness: Harness, view: FileView): string[] {
  if (harness.name !== "claude") {
    const file = harness.instructions.find((f) => view.exists(f));
    return file === undefined ? [] : [file];
  }
  const files = CLAUDE_FILES.filter((file) => view.exists(file));
  if (files.length === 0) return view.exists(AGENTS_MD) ? [AGENTS_MD] : [];
  const imported = files.some((file) => importsAgentsMd(view.read(file), file));
  return imported && view.exists(AGENTS_MD) ? [...files, AGENTS_MD] : files;
}

const FENCE = /^ {0,3}(`{3,}|~{3,})/;

// @decision(DL-055)
/**
 * Whether `content` of the instruction file `file` has an `@path` import that resolves to the
 * root AGENTS.md. Imports inside code spans and fenced code blocks do not count.
 */
export function importsAgentsMd(content: string, file: string): boolean {
  const dir = posix.dirname(file);
  /** The open fence's marker; a fence closes on the same character, at least as long. */
  let fence: string | undefined;
  for (const line of content.split(/\r?\n/)) {
    const marker = FENCE.exec(line)?.[1];
    if (marker !== undefined) {
      if (fence === undefined) fence = marker;
      else if (marker[0] === fence[0] && marker.length >= fence.length) fence = undefined;
      continue;
    }
    if (fence !== undefined) continue;
    const prose = line.replace(/`[^`]*`/g, "");
    for (const match of prose.matchAll(/(?:^|\s)@(\S+)/g)) {
      const target = match[1];
      if (target !== undefined && posix.normalize(posix.join(dir, target)) === AGENTS_MD) {
        return true;
      }
    }
  }
  return false;
}

// @decision(DL-054)
/** One warning per instruction file that block readers read instead of the block's file. */
function blindWarnings(
  blockFiles: readonly string[],
  blind: readonly Harness[],
  reads: (harness: Harness) => string | undefined,
): string[] {
  const byFile = new Map<string, Harness[]>();
  for (const harness of blind) {
    const file = reads(harness) ?? harness.instructions[0] ?? AGENTS_MD;
    byFile.set(file, [...(byFile.get(file) ?? []), harness]);
  }
  return [...byFile].map(([file, harnesses]) => {
    const names = harnesses.map((h) => h.title).join(" and ");
    const one = harnesses.length === 1;
    return `The dld-kit rule block is in ${blockFiles.join(" and ")}, but ${names} ${one ? "reads" : "read"} ${file}. To cover ${one ? "it" : "them"}, move the block (the dld-kit:start line through the dld-kit:end line) into ${file}, then run dld install-rule.`;
  });
}

/** The instruction file a new block goes into. Only regular files are edited or created. */
function blockPlacement(ctx: Context, root: string): string {
  for (const file of [AGENTS_MD, CLAUDE_MD]) {
    if (ctx.fs.isRegularFile(join(root, file))) return file;
  }
  if (ctx.fs.lexists(join(root, AGENTS_MD))) {
    throw new DldError(
      `${AGENTS_MD} is not a regular file (a symlink?); dld-kit does not edit through it. Point it at a regular file or add the dld-kit block by hand.`,
    );
  }
  return AGENTS_MD;
}

const LEGACY_HEADING = /^## DLD \(Decision-Linked Development\)\s*$/;

// @decision(DL-043)
/** A warning for the hand-written DLD block the pre-1.0 dld-init skill appended to CLAUDE.md. */
function legacyBlockWarnings(claudeMd: string, ruleInstalled: boolean): string[] {
  const span = findBlock(claudeMd, CLAUDE_MD);
  const outside =
    span === undefined ? claudeMd : claudeMd.slice(0, span.from) + claudeMd.slice(span.to);
  if (!outside.split(/\r?\n/).some((line) => LEGACY_HEADING.test(line))) return [];
  const section =
    "CLAUDE.md has a '## DLD (Decision-Linked Development)' section from an older dld-init.";
  return [
    ruleInstalled
      ? `${section} dld-kit now installs the rule separately, so that section can be removed.`
      : `${section} Install the rule with dld install-rule --agent <name> before removing it.`,
  ];
}

// @decision(DL-049) @decision(DL-055)
/**
 * Whether `harness` already loads the rule under `root`: its owned rule file exists, or an
 * instruction file it reads holds the managed block or the pre-1.0 DLD section.
 */
export function loadsRule(ctx: Context, root: string, harness: Harness): boolean {
  if (harness.rule !== "block" && ctx.fs.exists(join(root, RULE_FILES[harness.rule]))) {
    return true;
  }
  const view = projectView(ctx, root);
  return instructionFiles(harness, view).some((file) =>
    view
      .read(file)
      .split(/\r?\n/)
      .some((line) => line === BLOCK_START || LEGACY_HEADING.test(line)),
  );
}

// @decision(DL-049)
/**
 * The rule text to add to a session of `harness` in the project at `root`, or undefined when
 * the project does not use DLD or the harness loads the rule already.
 */
export function sessionContext(
  ctx: Context,
  root: string,
  harness: Harness,
  text: string = RULE_TEXT,
): string | undefined {
  if (!ctx.fs.exists(join(root, CONFIG_FILE))) return undefined;
  return loadsRule(ctx, root, harness) ? undefined : text;
}

/** The first of `dir` (relative to `root`) and its parents under `root` that is a symlink. */
function symlinkedPart(ctx: Context, root: string, dir: string): string | undefined {
  let current = "";
  for (const part of dir.split("/")) {
    current = current === "" ? part : `${current}/${part}`;
    const full = join(root, current);
    if (!ctx.fs.lexists(full)) return undefined;
    if (!ctx.fs.exists(full) || ctx.fs.realPath(full) !== join(ctx.fs.realPath(root), current)) {
      return current;
    }
  }
  return undefined;
}

// @decision(DL-043)
/** Fails if `dir` (relative to `root`) or a parent under `root` is a symlink: installs never write through one. */
export function refuseSymlinkedDir(ctx: Context, root: string, dir: string): void {
  const linked = symlinkedPart(ctx, root, dir);
  if (linked !== undefined) {
    throw new DldError(
      `${linked} is a symlink; dld-kit does not install through symlinks. Replace it with a directory (dld-kit keeps each agent's copy separate).`,
    );
  }
}

/** The rule channels already installed under `root`. */
export function installedRuleChannels(ctx: Context, root: string): Set<RuleChannel> {
  const channels = new Set<RuleChannel>();
  for (const channel of ["claude-file", "agents-file"] as const) {
    if (ctx.fs.lexists(join(root, RULE_FILES[channel]))) channels.add(channel);
  }
  // @decision(DL-055)
  if (importFileVersion(projectView(ctx, root).read(CLAUDE_IMPORT_FILE)) !== undefined) {
    channels.add("claude-file");
  }
  for (const file of [AGENTS_MD, CLAUDE_MD]) {
    const path = join(root, file);
    if (ctx.fs.isRegularFile(path) && findBlock(ctx.fs.readFile(path), file) !== undefined) {
      channels.add("block");
    }
  }
  return channels;
}

/** Each installed rule file and block with the version in its notice. */
export function installedRuleStamps(
  ctx: Context,
  root: string,
): { path: string; version: string | undefined }[] {
  const stamps: { path: string; version: string | undefined }[] = [];
  const regular = (file: string) => ctx.fs.isRegularFile(join(root, file));
  for (const file of [CLAUDE_RULE_FILE, AGENTS_RULE_FILE].filter(regular)) {
    stamps.push({ path: file, version: ruleVersion(ctx.fs.readFile(join(root, file))) });
  }
  const imported = importFileVersion(projectView(ctx, root).read(CLAUDE_IMPORT_FILE));
  if (imported !== undefined) stamps.push({ path: CLAUDE_IMPORT_FILE, version: imported });
  for (const file of [AGENTS_MD, CLAUDE_MD].filter(regular)) {
    const content = ctx.fs.readFile(join(root, file));
    const span = findBlock(content, file);
    if (span !== undefined) {
      stamps.push({ path: file, version: ruleVersion(content.slice(span.from, span.to)) });
    }
  }
  return stamps;
}

/** Applies a plan: writes are atomic (DL-015); parents are created as needed. */
export function applyRulePlan(ctx: Context, root: string, plan: RulePlan): void {
  for (const { path, content } of plan.writes) {
    const full = join(root, path);
    ctx.fs.mkdir(dirname(full));
    if (ctx.fs.lexists(full) && !ctx.fs.isRegularFile(full)) ctx.fs.remove(full);
    writeFileAtomic(ctx, full, content);
  }
  for (const path of plan.removals) {
    const full = join(root, path);
    ctx.fs.remove(full);
    if (ctx.fs.isDirectory(dirname(full)) && ctx.fs.readDir(dirname(full)).length === 0) {
      ctx.fs.removeDir(dirname(full));
    }
  }
}
