import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync, symlinkSync } from "node:fs";
import { join } from "node:path";
import { fakeContext, memoryFs, tempProject } from "../test-helpers.ts";
import { findHarness, type Harness, type RuleChannel } from "./harnesses.ts";
import {
  AGENTS_RULE_FILE,
  applyRulePlan,
  BLOCK_END,
  BLOCK_START,
  CLAUDE_RULE_FILE,
  findBlock,
  installedRuleChannels,
  installedRuleStamps,
  loadsRule,
  planRule,
  RULE_TEXT,
  renderBlock,
  renderRuleFile,
  ruleVersion,
  sessionContext,
  upsertBlock,
} from "./rule.ts";

const TEXT = "# Rule\n\nLook things up.\n";
const NOTICE =
  "<!-- Generated by dld-kit 1.0.0 from templates/rules/dld-workflow.md. Do not edit: updating the rule overwrites this";
const BLOCK = renderBlock(TEXT, "1.0.0");

function plan(files: Record<string, string>, channels: RuleChannel[], codex = false) {
  const fs = memoryFs(files);
  const ctx = fakeContext({ fs });
  const result = planRule(ctx, "/p", new Set(channels), "1.0.0", { codex }, TEXT);
  return { fs, ctx, result };
}

describe("rendering", () => {
  test("owned rule files carry the notice; Antigravity's is marked always_on", () => {
    expect(renderRuleFile("claude-file", TEXT, "1.0.0")).toBe(`${NOTICE} file. -->\n\n${TEXT}`);
    expect(renderRuleFile("agents-file", TEXT, "1.0.0")).toStartWith(
      "---\ntrigger: always_on\n---\n<!-- Generated by dld-kit 1.0.0 ",
    );
    expect(ruleVersion(renderRuleFile("claude-file", TEXT, "2.1.0-rc.1"))).toBe("2.1.0-rc.1");
    expect(ruleVersion("no stamp")).toBeUndefined();
  });

  test("the block runs from start marker to end marker", () => {
    expect(BLOCK).toEqual([
      BLOCK_START,
      `${NOTICE} block. -->`,
      "",
      "# Rule",
      "",
      "Look things up.",
      BLOCK_END,
    ]);
  });

  test("the real rule text names skills, not slash commands", () => {
    expect(RULE_TEXT).toContain("the dld-lookup skill");
    expect(RULE_TEXT).not.toMatch(/`\/dld-/);
    expect(RULE_TEXT).toContain("`@decision(DL-XXX)`");
  });
});

describe("findBlock and upsertBlock", () => {
  const withBlock = `# Mine\n\n${BLOCK.join("\n")}\ntail\n`;

  test("finds the span between the markers", () => {
    const span = findBlock(withBlock, "AGENTS.md");
    expect(withBlock.slice(span?.from, span?.to)).toBe(BLOCK.join("\n"));
    expect(findBlock("# nothing\n", "AGENTS.md")).toBeUndefined();
  });

  test.each([
    ["a start without an end", `${BLOCK_START}\nx\n`],
    ["an end without a start", `x\n${BLOCK_END}\n`],
    ["an end before the start", `${BLOCK_END}\n${BLOCK_START}\n`],
    ["two blocks", `${BLOCK.join("\n")}\n${BLOCK.join("\n")}\n`],
  ])("rejects %s", (_, content) => {
    expect(() => findBlock(content, "AGENTS.md")).toThrow(
      "AGENTS.md: expected one '<!-- dld-kit:start -->' line followed by one",
    );
  });

  test("appends to empty, newline-terminated and unterminated files", () => {
    const block = BLOCK.join("\n");
    expect(upsertBlock("", BLOCK, "f")).toBe(`${block}\n`);
    expect(upsertBlock("# Mine\n", BLOCK, "f")).toBe(`# Mine\n\n${block}\n`);
    expect(upsertBlock("# Mine", BLOCK, "f")).toBe(`# Mine\n\n${block}\n`);
  });

  test("replaces the block in place and leaves the rest byte for byte", () => {
    const old = withBlock.replace("Look things up.", "Old text.");
    expect(upsertBlock(old, BLOCK, "f")).toBe(withBlock);
    expect(upsertBlock(withBlock, BLOCK, "f")).toBe(withBlock);
  });

  test("keeps CRLF line endings", () => {
    const crlf = `# Mine\r\n\r\n${BLOCK_START}\r\nold\r\n${BLOCK_END}\r\nend`;
    expect(upsertBlock(crlf, BLOCK, "f")).toBe(`# Mine\r\n\r\n${BLOCK.join("\r\n")}\r\nend`);
    expect(upsertBlock("# Mine\r\n", BLOCK, "f")).toBe(`# Mine\r\n\r\n${BLOCK.join("\r\n")}\r\n`);
  });
});

describe("planRule", () => {
  const block = `${BLOCK.join("\n")}\n`;
  const claudeRule = renderRuleFile("claude-file", TEXT, "1.0.0");

  test("Claude Code alone gets its own rule file", () => {
    const { result } = plan({}, ["claude-file"]);
    expect(result).toEqual({
      writes: [{ path: CLAUDE_RULE_FILE, content: claudeRule }],
      removals: [],
      warnings: [],
    });
  });

  test("the block goes into an existing AGENTS.md; Claude Code still reads CLAUDE.md", () => {
    const { result } = plan({ "/p/AGENTS.md": "# A\n", "/p/CLAUDE.md": "# C\n" }, [
      "claude-file",
      "block",
    ]);
    expect(result.writes).toEqual([
      { path: "AGENTS.md", content: `# A\n\n${block}` },
      { path: CLAUDE_RULE_FILE, content: claudeRule },
    ]);
  });

  test("with only CLAUDE.md, the block goes there and replaces Claude's rule file", () => {
    const { result } = plan({ "/p/CLAUDE.md": "# C\n", [`/p/${CLAUDE_RULE_FILE}`]: "old" }, [
      "claude-file",
      "block",
    ]);
    expect(result.writes).toEqual([{ path: "CLAUDE.md", content: `# C\n\n${block}` }]);
    expect(result.removals).toEqual([CLAUDE_RULE_FILE]);
    expect(result.warnings).toEqual([]);
  });

  test("warns when the block lands in CLAUDE.md and Codex is selected", () => {
    const { result } = plan({ "/p/CLAUDE.md": "# C\n" }, ["block"], true);
    expect(result.warnings).toEqual([
      expect.stringContaining("The dld-kit rule block is in CLAUDE.md, but Codex reads only"),
    ]);
  });

  test("with neither file, a new AGENTS.md holds the block, which Claude Code then reads", () => {
    const { result } = plan({}, ["claude-file", "block"]);
    expect(result.writes).toEqual([{ path: "AGENTS.md", content: block }]);
    expect(result.removals).toEqual([]);
  });

  test("Antigravity gets its own file unless the block is in AGENTS.md", () => {
    expect(plan({ "/p/CLAUDE.md": "" }, ["agents-file", "block"]).result.writes).toEqual([
      { path: "CLAUDE.md", content: block },
      { path: AGENTS_RULE_FILE, content: renderRuleFile("agents-file", TEXT, "1.0.0") },
    ]);
    const { result } = plan({ "/p/AGENTS.md": "", [`/p/${AGENTS_RULE_FILE}`]: "old" }, [
      "agents-file",
      "block",
    ]);
    expect(result.writes).toEqual([{ path: "AGENTS.md", content: block }]);
    expect(result.removals).toEqual([AGENTS_RULE_FILE]);
  });

  test("an existing block is refreshed where it is, and an unchanged one is not rewritten", () => {
    const stale = block.replace("Look things up.", "Old.");
    const { result } = plan({ "/p/AGENTS.md": "# A\n", "/p/CLAUDE.md": stale }, ["block"]);
    expect(result.writes).toEqual([{ path: "CLAUDE.md", content: block }]);
    expect(plan({ "/p/CLAUDE.md": block }, ["block"]).result.writes).toEqual([]);
  });

  test("warns about the old hand-written CLAUDE.md section, but not about the block", () => {
    const legacy = "# Project\n\n## DLD (Decision-Linked Development)\r\n\nRules\n";
    expect(plan({ "/p/CLAUDE.md": legacy }, ["claude-file"]).result.warnings).toEqual([
      expect.stringContaining("from an older dld-init"),
    ]);
    const inBlock = upsertBlock("", renderBlock("## DLD (Decision-Linked Development)\n", "1"), "");
    expect(plan({ "/p/CLAUDE.md": inBlock }, ["block"]).result.warnings).toEqual([]);
  });

  test("never writes through a symlinked AGENTS.md", () => {
    const p = tempProject(null);
    try {
      p.write("docs/agents.md", "# Shared\n");
      symlinkSync("docs/agents.md", join(p.root, "AGENTS.md"));
      expect(() => planRule(p.ctx, p.root, new Set(["block"]), "1.0.0")).toThrow(
        "AGENTS.md is not a regular file",
      );
      p.write("CLAUDE.md", "# C\n");
      const result = planRule(p.ctx, p.root, new Set(["block"]), "1.0.0");
      expect(result.writes.map((w) => w.path)).toEqual(["CLAUDE.md"]);
    } finally {
      p.cleanup();
    }
  });
});

describe("planRule with symlinks and stale placements", () => {
  function linked(setup: (p: ReturnType<typeof tempProject>) => void) {
    const p = tempProject(null);
    setup(p);
    return p;
  }

  test("a CLAUDE.md linked to AGENTS.md reads the block, so Claude Code gets no rule file", () => {
    const p = linked((q) => {
      q.write("AGENTS.md", "# Shared\n");
      symlinkSync("AGENTS.md", join(q.root, "CLAUDE.md"));
    });
    try {
      const result = planRule(p.ctx, p.root, new Set(["claude-file", "block"]), "1.0.0");
      expect(result.writes.map((w) => w.path)).toEqual(["AGENTS.md"]);
    } finally {
      p.cleanup();
    }
  });

  test("an AGENTS.md linked to CLAUDE.md gets the block through CLAUDE.md, for Antigravity and Codex", () => {
    const p = linked((q) => {
      q.write("CLAUDE.md", "# Shared\n");
      symlinkSync("CLAUDE.md", join(q.root, "AGENTS.md"));
    });
    try {
      const result = planRule(p.ctx, p.root, new Set(["agents-file", "block"]), "1.0.0", {
        codex: true,
      });
      expect(result.writes.map((w) => w.path)).toEqual(["CLAUDE.md"]);
      expect(result.warnings).toEqual([]);
    } finally {
      p.cleanup();
    }
  });

  test("never writes an owned rule file through a symlinked directory", () => {
    const p = linked((q) => {
      q.write("elsewhere/x", "");
      symlinkSync("elsewhere", join(q.root, ".claude"));
    });
    try {
      expect(() => planRule(p.ctx, p.root, new Set(["claude-file"]), "1.0.0")).toThrow(
        ".claude is a symlink; dld-kit does not install through symlinks",
      );
    } finally {
      p.cleanup();
    }
  });

  test("warns Codex users about a block already in CLAUDE.md, with steps that work", () => {
    const inClaude = upsertBlock("# C\n", renderBlock(TEXT, "1.0.0"), "");
    const { result } = plan({ "/p/AGENTS.md": "# A\n", "/p/CLAUDE.md": inClaude }, ["block"], true);
    expect(result.writes).toEqual([]);
    expect(result.warnings).toEqual([
      expect.stringContaining(
        "move the block (the dld-kit:start line through the dld-kit:end line) into AGENTS.md",
      ),
    ]);
  });

  test("the old CLAUDE.md section is only called removable once a rule is installed", () => {
    const legacy = "## DLD (Decision-Linked Development)\n";
    expect(plan({ "/p/CLAUDE.md": legacy }, []).result.warnings).toEqual([
      expect.stringContaining(
        "Install the rule with dld install-rule --agent <name> before removing it.",
      ),
    ]);
  });
});

describe("installed rules", () => {
  test("reports the channels and stamps present", () => {
    const fs = memoryFs({
      [`/p/${CLAUDE_RULE_FILE}`]: renderRuleFile("claude-file", TEXT, "1.0.0"),
      [`/p/${AGENTS_RULE_FILE}`]: "hand-written",
      "/p/AGENTS.md": `# A\n\n${upsertBlock("", renderBlock(TEXT, "0.9.0"), "")}`,
      "/p/CLAUDE.md": "# no block\n",
    });
    const ctx = fakeContext({ fs });
    expect([...installedRuleChannels(ctx, "/p")]).toEqual(["claude-file", "agents-file", "block"]);
    expect(installedRuleStamps(ctx, "/p")).toEqual([
      { path: CLAUDE_RULE_FILE, version: "1.0.0" },
      { path: AGENTS_RULE_FILE, version: undefined },
      { path: "AGENTS.md", version: "0.9.0" },
    ]);
    expect(installedRuleChannels(fakeContext({ fs: memoryFs({}) }), "/p").size).toBe(0);
  });

  test("applyRulePlan writes files and removes stale ones", () => {
    const p = tempProject(null);
    try {
      p.write(AGENTS_RULE_FILE, "old");
      applyRulePlan(p.ctx, p.root, {
        writes: [{ path: CLAUDE_RULE_FILE, content: "rule\n" }],
        removals: [AGENTS_RULE_FILE],
        warnings: [],
      });
      expect(readFileSync(join(p.root, CLAUDE_RULE_FILE), "utf8")).toBe("rule\n");
      expect(installedRuleChannels(p.ctx, p.root)).toEqual(new Set(["claude-file"]));
      expect(existsSync(join(p.root, ".agents/rules"))).toBe(false);
      expect(existsSync(join(p.root, ".agents"))).toBe(true);
    } finally {
      p.cleanup();
    }
  });
});

describe("loadsRule and sessionContext", () => {
  const harness = (name: string): Harness => {
    const found = findHarness(name);
    if (found === undefined) throw new Error(name);
    return found;
  };
  const loads = (name: string, files: Record<string, string>) =>
    loadsRule(fakeContext({ fs: memoryFs(files) }), "/p", harness(name));
  const block = `# Notes\n\n${BLOCK.join("\n")}\n`;

  test("an owned rule file counts for its harness", () => {
    expect(loads("claude", { [`/p/${CLAUDE_RULE_FILE}`]: "x" })).toBe(true);
    expect(loads("antigravity", { [`/p/${AGENTS_RULE_FILE}`]: "x" })).toBe(true);
    expect(loads("claude", { [`/p/${AGENTS_RULE_FILE}`]: "x" })).toBe(false);
    expect(loads("codex", {})).toBe(false);
  });

  test("the block counts only in the instruction file the harness reads", () => {
    expect(loads("claude", { "/p/CLAUDE.md": block })).toBe(true);
    expect(loads("claude", { "/p/AGENTS.md": block })).toBe(true);
    expect(loads("claude", { "/p/AGENTS.md": block, "/p/CLAUDE.md": "# C\n" })).toBe(false);
    expect(loads("codex", { "/p/CLAUDE.md": block })).toBe(false);
    expect(loads("pi", { "/p/CLAUDE.md": block })).toBe(true);
    expect(loads("pi", { "/p/CLAUDE.md": block, "/p/AGENTS.md": "# A\n" })).toBe(false);
  });

  test("the pre-1.0 DLD section counts, CRLF included", () => {
    const legacy = "# C\r\n\r\n## DLD (Decision-Linked Development)\r\n\r\nRules.\r\n";
    expect(loads("claude", { "/p/CLAUDE.md": legacy })).toBe(true);
    expect(loads("claude", { "/p/CLAUDE.md": "# DLD (Decision-Linked Development)\n" })).toBe(
      false,
    );
  });

  test("sessionContext returns the text only in a DLD project that lacks the rule", () => {
    const context = (files: Record<string, string>) =>
      sessionContext(fakeContext({ fs: memoryFs(files) }), "/p", harness("claude"), TEXT);
    expect(context({ "/p/dld.config.yaml": "" })).toBe(TEXT);
    expect(context({ "/p/dld.config.yaml": "", "/p/CLAUDE.md": block })).toBeUndefined();
    expect(context({ "/p/CLAUDE.md": "# C\n" })).toBeUndefined();
  });
});
