import { dirname, join } from "node:path";
import ruleText from "../../templates/rules/dld-workflow.md" with { type: "text" };
import { CONFIG_FILE } from "../core/config.ts";
import type { Context } from "../core/context.ts";
import { DldError } from "../core/errors.ts";
import { writeFileAtomic } from "../core/files.ts";
import type { Harness, RuleChannel } from "./harnesses.ts";

// @decision(DL-042)
/** The always-on rule, embedded in the bundle so every copy of the CLI can install it. */
export const RULE_TEXT: string = ruleText;
export const RULE_SOURCE = "templates/rules/dld-workflow.md";

export const CLAUDE_RULE_FILE = ".claude/rules/dld-workflow.md";
export const AGENTS_RULE_FILE = ".agents/rules/dld-workflow.md";
export const BLOCK_START = "<!-- dld-kit:start -->";
export const BLOCK_END = "<!-- dld-kit:end -->";
/** Instruction files that can hold the block, in the order harnesses read them. */
const AGENTS_MD = "AGENTS.md";
const CLAUDE_MD = "CLAUDE.md";

type RuleFileChannel = Exclude<RuleChannel, "block">;
const RULE_FILES: Record<RuleFileChannel, string> = {
  "claude-file": CLAUDE_RULE_FILE,
  "agents-file": AGENTS_RULE_FILE,
};

// @decision(DL-044)
function notice(version: string, what: string): string {
  return `<!-- Generated by dld-kit ${version} from ${RULE_SOURCE}. Do not edit: updating the rule overwrites this ${what}. -->`;
}

const STAMP = /<!-- Generated by dld-kit (\S+) from /;

/** The dld-kit version in a rule file's or block's notice, if any. */
export function ruleVersion(content: string): string | undefined {
  return STAMP.exec(content)?.[1];
}

// @decision(DL-045)
/** An owned rule file's content. Antigravity only loads rules marked `always_on` every session. */
export function renderRuleFile(channel: RuleFileChannel, text: string, version: string): string {
  const frontmatter = channel === "agents-file" ? "---\ntrigger: always_on\n---\n" : "";
  return `${frontmatter}${notice(version, "file")}\n\n${text}`;
}

/** The managed block's lines, from start marker to end marker. */
export function renderBlock(text: string, version: string): string[] {
  const body = text.endsWith("\n") ? text.slice(0, -1) : text;
  return [BLOCK_START, notice(version, "block"), "", ...body.split("\n"), BLOCK_END];
}

interface BlockSpan {
  /** Offset of the start marker's first character. */
  from: number;
  /** Offset just past the end marker, before its line terminator. */
  to: number;
}

// @decision(DL-045)
/** Where the block sits in `content`, or undefined if there is none. Bad markers are an error. */
export function findBlock(content: string, file: string): BlockSpan | undefined {
  const starts: number[] = [];
  const ends: number[] = [];
  let offset = 0;
  for (const line of content.split("\n")) {
    const text = line.endsWith("\r") ? line.slice(0, -1) : line;
    if (text === BLOCK_START) starts.push(offset);
    if (text === BLOCK_END) ends.push(offset);
    offset += line.length + 1;
  }
  if (starts.length === 0 && ends.length === 0) return undefined;
  const [from] = starts;
  const [end] = ends;
  if (starts.length !== 1 || ends.length !== 1 || from === undefined || end === undefined) {
    throw malformed(file);
  }
  if (end < from) throw malformed(file);
  return { from, to: end + BLOCK_END.length };
}

function malformed(file: string): DldError {
  return new DldError(
    `${file}: expected one '${BLOCK_START}' line followed by one '${BLOCK_END}' line; fix the dld-kit markers by hand`,
  );
}

// @decision(DL-045)
/**
 * `content` with the block replaced, or appended after a blank line. Everything outside the
 * block is unchanged, and the block uses the file's line endings.
 */
export function upsertBlock(content: string, block: readonly string[], file: string): string {
  const eol = content.includes("\r\n") ? "\r\n" : "\n";
  const rendered = block.join(eol);
  const span = findBlock(content, file);
  if (span !== undefined) return content.slice(0, span.from) + rendered + content.slice(span.to);
  if (content === "") return rendered + eol;
  const separator = content.endsWith("\n") ? eol : eol + eol;
  return content + separator + rendered + eol;
}

export interface RulePlan {
  /** Files to write, relative to the project root. */
  writes: { path: string; content: string }[];
  /** Owned rule files to delete, relative to the project root. */
  removals: string[];
  warnings: string[];
}

export interface RuleOptions {
  /** Codex is among the selected harnesses; it reads only AGENTS.md. */
  codex?: boolean;
}

// @decision(DL-045)
/**
 * What installing the rule for `channels` changes under `root`. A block already present in
 * AGENTS.md or CLAUDE.md is refreshed where it is; otherwise a new one goes into AGENTS.md, else
 * CLAUDE.md, else a new AGENTS.md. A harness that loads the block's file gets no owned rule file.
 */
export function planRule(
  ctx: Context,
  root: string,
  channels: ReadonlySet<RuleChannel>,
  version: string,
  { codex = false }: RuleOptions = {},
  text: string = RULE_TEXT,
): RulePlan {
  const plan: RulePlan = { writes: [], removals: [], warnings: [] };
  const regular = (file: string) => ctx.fs.isRegularFile(join(root, file));
  const read = (file: string) => (regular(file) ? ctx.fs.readFile(join(root, file)) : "");
  /** The file a harness ends up reading, following symlinks; a file yet to be created is itself. */
  const resolved = (file: string) => {
    const full = join(root, file);
    return ctx.fs.exists(full) ? ctx.fs.realPath(full) : full;
  };

  let blockFiles = [AGENTS_MD, CLAUDE_MD].filter(
    (file) => regular(file) && findBlock(read(file), file) !== undefined,
  );
  if (blockFiles.length === 0 && channels.has("block")) blockFiles = [blockPlacement(ctx, root)];
  for (const file of blockFiles) {
    const content = read(file);
    const updated = upsertBlock(content, renderBlock(text, version), file);
    if (updated !== content) plan.writes.push({ path: file, content: updated });
  }

  const withBlock = new Set(blockFiles.map(resolved));
  const loads = (file: string) => withBlock.has(resolved(file));
  // Claude Code reads CLAUDE.md, or AGENTS.md when there is none; Antigravity and Codex read AGENTS.md.
  const claudeReads = ctx.fs.exists(join(root, CLAUDE_MD)) ? CLAUDE_MD : AGENTS_MD;
  const loadsBlock: Record<RuleFileChannel, boolean> = {
    "claude-file": loads(claudeReads),
    "agents-file": loads(AGENTS_MD),
  };
  if (codex && blockFiles.length > 0 && !loads(AGENTS_MD)) {
    plan.warnings.push(
      "The dld-kit rule block is in CLAUDE.md, but Codex reads only AGENTS.md. To cover Codex, move the block (the dld-kit:start line through the dld-kit:end line) into AGENTS.md, then run dld install-rule. Pi and OpenCode read AGENTS.md instead of CLAUDE.md once it exists.",
    );
  }
  for (const channel of ["claude-file", "agents-file"] as const) {
    const path = RULE_FILES[channel];
    if (loadsBlock[channel]) {
      if (ctx.fs.lexists(join(root, path))) plan.removals.push(path);
    } else if (channels.has(channel)) {
      refuseSymlinkedDir(ctx, root, dirname(path));
      const content = renderRuleFile(channel, text, version);
      if (read(path) !== content) plan.writes.push({ path, content });
    }
  }
  const ruleInstalled = blockFiles.length > 0 || channels.size > 0;
  plan.warnings.push(...legacyBlockWarnings(read(CLAUDE_MD), ruleInstalled));
  return plan;
}

/** The instruction file a new block goes into. Only regular files are edited or created. */
function blockPlacement(ctx: Context, root: string): string {
  for (const file of [AGENTS_MD, CLAUDE_MD]) {
    if (ctx.fs.isRegularFile(join(root, file))) return file;
  }
  if (ctx.fs.lexists(join(root, AGENTS_MD))) {
    throw new DldError(
      `${AGENTS_MD} is not a regular file (a symlink?); dld-kit does not edit through it. Point it at a regular file or add the dld-kit block by hand.`,
    );
  }
  return AGENTS_MD;
}

const LEGACY_HEADING = /^## DLD \(Decision-Linked Development\)\s*$/;

// @decision(DL-043)
/** A warning for the hand-written DLD block the pre-1.0 dld-init skill appended to CLAUDE.md. */
function legacyBlockWarnings(claudeMd: string, ruleInstalled: boolean): string[] {
  const span = findBlock(claudeMd, CLAUDE_MD);
  const outside =
    span === undefined ? claudeMd : claudeMd.slice(0, span.from) + claudeMd.slice(span.to);
  if (!outside.split(/\r?\n/).some((line) => LEGACY_HEADING.test(line))) return [];
  const section =
    "CLAUDE.md has a '## DLD (Decision-Linked Development)' section from an older dld-init.";
  return [
    ruleInstalled
      ? `${section} dld-kit now installs the rule separately, so that section can be removed.`
      : `${section} Install the rule with dld install-rule --agent <name> before removing it.`,
  ];
}

// @decision(DL-049)
/**
 * Whether `harness` already loads the rule under `root`: its owned rule file exists, or the
 * instruction file it reads holds the managed block or the pre-1.0 DLD section.
 */
export function loadsRule(ctx: Context, root: string, harness: Harness): boolean {
  if (harness.rule !== "block" && ctx.fs.exists(join(root, RULE_FILES[harness.rule]))) {
    return true;
  }
  const file = harness.instructions.find((name) => ctx.fs.exists(join(root, name)));
  if (file === undefined) return false;
  return ctx.fs
    .readFile(join(root, file))
    .split(/\r?\n/)
    .some((line) => line === BLOCK_START || LEGACY_HEADING.test(line));
}

// @decision(DL-049)
/**
 * The rule text to add to a session of `harness` in the project at `root`, or undefined when
 * the project does not use DLD or the harness loads the rule already.
 */
export function sessionContext(
  ctx: Context,
  root: string,
  harness: Harness,
  text: string = RULE_TEXT,
): string | undefined {
  if (!ctx.fs.exists(join(root, CONFIG_FILE))) return undefined;
  return loadsRule(ctx, root, harness) ? undefined : text;
}

// @decision(DL-043)
/** Fails if `dir` (relative to `root`) or a parent under `root` is a symlink: installs never write through one. */
export function refuseSymlinkedDir(ctx: Context, root: string, dir: string): void {
  let current = "";
  for (const part of dir.split("/")) {
    current = current === "" ? part : `${current}/${part}`;
    const full = join(root, current);
    if (!ctx.fs.lexists(full)) return;
    if (!ctx.fs.exists(full) || ctx.fs.realPath(full) !== join(ctx.fs.realPath(root), current)) {
      throw new DldError(
        `${current} is a symlink; dld-kit does not install through symlinks. Replace it with a directory (dld-kit keeps each agent's copy separate).`,
      );
    }
  }
}

/** The rule channels already installed under `root`. */
export function installedRuleChannels(ctx: Context, root: string): Set<RuleChannel> {
  const channels = new Set<RuleChannel>();
  for (const channel of ["claude-file", "agents-file"] as const) {
    if (ctx.fs.lexists(join(root, RULE_FILES[channel]))) channels.add(channel);
  }
  for (const file of [AGENTS_MD, CLAUDE_MD]) {
    const path = join(root, file);
    if (ctx.fs.isRegularFile(path) && findBlock(ctx.fs.readFile(path), file) !== undefined) {
      channels.add("block");
    }
  }
  return channels;
}

/** Each installed rule file and block with the version in its notice. */
export function installedRuleStamps(
  ctx: Context,
  root: string,
): { path: string; version: string | undefined }[] {
  const stamps: { path: string; version: string | undefined }[] = [];
  const regular = (file: string) => ctx.fs.isRegularFile(join(root, file));
  for (const file of [CLAUDE_RULE_FILE, AGENTS_RULE_FILE].filter(regular)) {
    stamps.push({ path: file, version: ruleVersion(ctx.fs.readFile(join(root, file))) });
  }
  for (const file of [AGENTS_MD, CLAUDE_MD].filter(regular)) {
    const content = ctx.fs.readFile(join(root, file));
    const span = findBlock(content, file);
    if (span !== undefined) {
      stamps.push({ path: file, version: ruleVersion(content.slice(span.from, span.to)) });
    }
  }
  return stamps;
}

/** Applies a plan: writes are atomic (DL-015); parents are created as needed. */
export function applyRulePlan(ctx: Context, root: string, plan: RulePlan): void {
  for (const { path, content } of plan.writes) {
    const full = join(root, path);
    ctx.fs.mkdir(dirname(full));
    if (ctx.fs.lexists(full) && !ctx.fs.isRegularFile(full)) ctx.fs.remove(full);
    writeFileAtomic(ctx, full, content);
  }
  for (const path of plan.removals) {
    const full = join(root, path);
    ctx.fs.remove(full);
    if (ctx.fs.isDirectory(dirname(full)) && ctx.fs.readDir(dirname(full)).length === 0) {
      ctx.fs.removeDir(dirname(full));
    }
  }
}
